services:
  shlink_dashboard_node:
    container_name: shlink_dashboard_node
    user: 1000:1000
    image: node:22.12-alpine
    command: /bin/sh -c "cd /home/shlink-dashboard && npm install && node --run start"
    volumes:
      - ./:/home/shlink-dashboard
    ports:
      - "3005:3005"
      - "24678:24678" # Vite dev server web socket port
    links:
      - shlink_dashboard_db_postgres
    environment:
      SHLINK_DASHBOARD_DB_DRIVER: postgres
      SHLINK_DASHBOARD_DB_HOST: shlink_dashboard_db_postgres
      SHLINK_DASHBOARD_DB_PORT: 5432
      SHLINK_DASHBOARD_DB_NAME: shlink_dashboard
      SHLINK_DASHBOARD_DB_USER: postgres
      SHLINK_DASHBOARD_DB_PASSWORD: root
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  shlink_dashboard_db_postgres:
    container_name: shlink_dashboard_db_postgres
    user: 1000:1000
    image: postgres:16.2-alpine
    ports:
      - "5435:5432"
    volumes:
      - ./:/home/shlink-dashboard
      - ./data/infra/database_pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shlink_dashboard
      PGDATA: /var/lib/postgresql/data/pgdata

#  # Production docker image linked with the dev database
#  shlink_dashboard_testing:
#    build:
#      context: .
#    user: 1000:1000
#    image: shlink_dashboard_testing
#    ports:
#      - "3006:3006"
#    links:
#      - shlink_dashboard_db_postgres
#    environment:
#      SHLINK_DASHBOARD_DB_DRIVER: postgres
#      SHLINK_DASHBOARD_DB_HOST: shlink_dashboard_db_postgres
#      SHLINK_DASHBOARD_DB_PORT: 5432
#      SHLINK_DASHBOARD_DB_NAME: shlink_dashboard
#      SHLINK_DASHBOARD_DB_USER: postgres
#      SHLINK_DASHBOARD_DB_PASSWORD: root
#      SHLINK_DASHBOARD_PORT: 3006
#      NODE_ENV: production
