blank_issues_enabled: false
contact_links:
  - name: Question - Support
    about: Do you need help setting up or using Shlink Dashboard?
    url: https://github.com/orgs/shlinkio/discussions/new?category=help-wanted
